---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.17.1

inputs:
  - name: dp-apipoc-server

outputs:
  - name: build

run:
  path: dp-apipoc-server/ci/scripts/build.sh
