---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-git

inputs:
  - name: artifacts
  - name: dp-api-poc

outputs:
  - name: deployment

run:
  path: dp-api-poc/ci/scripts/deployment-bundle.sh
