---
resources:
- name: project-src
  type: git
  source:
    uri: https://github.com/ONSdigital/dp-apipoc-server.git
    branch: develop
- name: elasticns
  type: docker-image
  source:
    repository: sem247/elasticns
    tag: "2.4.3_1"
- name: zbdreader
  type: docker-image
  source:
    repository: sem247/zbdreader
    tag: "1.0.0"
- name: devtools
  type: docker-image
  source:
    repository: sem247/dp-apipoc-devtools
    tag: "1.0.1"
- name: dp-apipoc-spec_image
  type: docker-image
  source:
   repository: {{docker_apipoc-spec}}
   email: {{docker_mail}}
   username: {{docker_user}}
   password: {{docker_pass}}
- name: dp-apipoc-server_image
  type: docker-image
  source:
   repository: {{docker_apipoc-server}}
   email: {{docker_mail}}
   username: {{docker_user}}
   password: {{docker_pass}}

jobs:
- name: java-unit-tests-job
  plan:
  - get: project-src
    trigger: true
  - task: Run Java client unit tests
    file: project-src/tests/java/java-unit-tests-task.yml
- name: build-java-client-artefact-job
  plan:
  - get: project-src
    passed: [java-unit-tests-job]
    trigger: true
  - task: Build Java client jar artefact
    file: project-src/tests/java/java-client-jar-task.yml
- name: bdd-tests-job
  plan:
  - aggregate:
    - get: project-src
      passed: [java-unit-tests-job]
      trigger: true
    - get: elasticns
      params:
        save: true
    - get: zbdreader
      params:
        save: true
    - get: devtools
      params:
        save: true
  - task: Run BDD tests
    privileged: true
    file: project-src/java-bdd-tests-task.yml
- name: build-artefact-images-job
  plan:
  - get: project-src
    passed: [bdd-tests-job]
    trigger: true
  - put: dp-apipoc-server_image
    params:
      build: project-src
  - put: dp-apipoc-spec_image
    params:
      build: project-src/doc